services:
  postgres:
    image: postgres:16.3
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: demoDB
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - app_network

  neo4j:
    image: neo4j:5.12-community
    container_name: my_neo4j
    environment:
      NEO4J_AUTH: neo4j/dumb_password
      NEO4J_server.memory.pagecache.size: 512M
      NEO4J_server.memory.heap.initial_size: 512M
      NEO4J_server.memory.heap.max_size: 1024M
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/conf
      - neo4j_plugins:/plugins
    ports:
      - "7474:7474"  # HTTP Neo4j Browser
      - "7687:7687"  # Bolt Protocol
    networks:
      - app_network

  # data-generator:
  #   build:
  #     context: ./data_generator
  #   depends_on:
  #     - postgres
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: "5432"
  #     DB_NAME: demoDB
  #     DB_USER: admin
  #     DB_PASSWORD_FILE: /run/secrets/db_password
  #   secrets:
  #     - db_password
  #   networks:
  #     - app_network

  config-generator:
    image: alpine:latest
    volumes:
      - app-config:/app/config
      - ./config.yaml:/app/config/config.orig.yaml
    secrets:
      - db_password
      - jwt_key
    entrypoint: >
      sh -c "
        echo 'Generating YAML config from template...';
        cp /app/config/config.orig.yaml /app/config/config.yaml;

        apk add --no-cache yq;
        yq eval '.storage_config.db_config.password = strload(\"/run/secrets/db_password\") | .server_config.jwt_key = strload(\"/run/secrets/jwt_key\")' /app/config/config.yaml -i;
      "

  app:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    container_name: social
    depends_on:
      config-generator:
        condition: "service_completed_successfully"
      postgres:
        condition: "service_started"
      neo4j:
        condition: "service_started"
    environment:
      CONFIG_PATH: /app/config/config.yaml
    volumes:
      - app-config:/app/config
    ports:
      - "15000:15000"
    networks:
      - app_network

networks:
  app_network:

volumes:
  pgdata:
  app-config:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
  neo4j_plugins:

secrets:
  jwt_key:
    file: ../secrets/jwt_key.txt
  db_password:
    file: ../secrets/db_password.txt
